// @ts-check

/**
 * The sidebar is generated from the folder structure under `docs/`.
 * Ordering comes from `_category_.json` (`position`) per folder and
 * `sidebar_position` in each page's front matter.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
